version: '2'

services:
  site:
    build:
      context: ./
    volumes:
      - $PWD:/root:ro
    networks:
      - reverse-proxy
    restart: always
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: mmo.soywiz.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_EMAIL: soywiz@gmail.com
      LETSENCRYPT_HOST: mmo.soywiz.com
  redis:
    #container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - $PWD/data/redis:/data
    restart: always
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
