version: '2'

services:
  site:
    build:
      context: ./
    networks:
      - reverse-proxy
    restart: always
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: mmo.soywiz.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_EMAIL: soywiz@gmail.com
      LETSENCRYPT_HOST: mmo.soywiz.com
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
